name: Build Whole App

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libusb-1.0-0-dev qtbase5-dev qtdeclarative5-dev qtquickcontrols2-5-dev qtmodern-
          # Примечание: ставим зависимости для сборки ядра и Qt5 на Ubuntu

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cbindgen
        run: cargo install cbindgen

      - name: Build Rust Core
        run: |
          cargo build --release

      - name: Generate C Header
        run: |
          mkdir -p include
          cbindgen --config core/cbindgen.toml --crate dspi-core --output include/dspi_core.h

      - name: Build Qt GUI
        run: |
          cd qt
          mkdir build && cd build
          cmake ..
          make -j$(nproc)

      - name: Upload Ready Application
        uses: actions/upload-artifact@v4
        with:
          name: dspi-console-linux
          path: qt/build/DSPiConsole
